[package]

name = "gif"
license = "MIT"
version = "0.5.0"
description = "GIF de- and encoder"
authors = ["nwin <nwin@users.noreply.github.com>"]
readme = "README.md"
repository = "https://github.com/PistonDevelopers/image-gif.git"
documentation = "http://www.piston.rs/image/gif/index.html"
homepage = "https://github.com/PistonDevelopers/image-gif"

exclude = [
    "tests/*",
]

[dependencies]
lzw = "0.8"
color_quant = "1.0"

[dev-dependencies]
glob = "*"

[features]
default = ["raii_no_panic"]

raii_no_panic = []
c_api = ["libc"]

[dependencies.libc]
version = "0.1"
optional = true
